import React, { createContext, useContext, useState, useEffect, useRef } from "react";
import {
  mockPodcasts,
  mockEpisodes,
  mockViralClips,
  mockEmotionTimeline,
  mockKnowledge,
  mockAudienceInsights,
  mockPerspectives
} from "../utils/mockData";
import { VectorStore } from "../utils/vectorDb";

const EPISODE_TOPICS = {
  e1: [
    {
      keywords: ["lost generation", "displacement", "job", "worker", "craftsmen", "masons"],
      concept: "The Lost Generation & Job Displacement",
      explanation: "how heavy industrial automation and bricklaying robots are stepping in to address labor shortages while risking the displacement of young manual builders.",
      notes: "the host recommends establishing vocational upskilling programs to train masons to supervise, program, and maintain these robotic systems on-site.",
      implication: "this requires balancing rapid construction scaling with proactive human workforce adaptation and retraining."
    },
    {
      keywords: ["robot", "automation", "machine", "help", "technology", "redrow", "barratt"],
      concept: "Construction Robotics & Automation",
      explanation: "the deployment of robotic bricklayers by builders like Barratt Redrow to accelerate home building and maintain operational pace.",
      notes: "while automation handles repetitive tasks, human masons are still required to direct the layout and troubleshoot mechanical deviations.",
      implication: "the shift raises capital investment barriers for construction firms while stabilizing long-term output."
    },
    {
      keywords: ["challenges", "cost", "rebuild", "capital", "expenditure"],
      concept: "Implementation Challenges & Capital Cost",
      explanation: "the high capital expenditure (CapEx) involved in acquiring and deploying robotic bricklayers on-site.",
      notes: "firms must offset high initial equipment costs with long-term efficiency gains and reduced dependency on scarce manual labor.",
      implication: "smaller contractors may face consolidation pressure, while larger developers gain technical scale."
    }
  ],
  e2: [
    {
      keywords: ["dating", "inflation", "living", "cost", "economics"],
      concept: "Dating Economics & Rising Costs",
      explanation: "how the modern cost-of-living crunch is fundamentally shifting dating habits, forcing younger demographics to seek lower-cost date alternatives.",
      notes: "daters are increasingly avoiding expensive dinners or cocktail bars in favor of low-pressure creative options like coffee walks.",
      implication: "macroeconomic inflation directly changes the social protocols and spending choices in courtship."
    },
    {
      keywords: ["virtual", "screen", "video", "call", "compatibility"],
      concept: "Virtual Screenings & Compatibility",
      explanation: "the rising use of short video calls as pre-date screening mechanisms to verify mutual compatibility and save money.",
      notes: "this filter helps daters avoid investing in expensive in-person meetings with individuals who lack chemistry.",
      implication: "digital pre-screening reduces friction and financial waste, making dating matches more intentional."
    },
    {
      keywords: ["hinge", "ceo", "app", "interface", "product"],
      concept: "App Interface Redesign & Engagement Loops",
      explanation: "how Hinge's executive leadership is adjusting product design and algorithms to align with budget-conscious daters.",
      notes: "the app incorporates features highlighting low-cost local date ideas and facilitating seamless virtual screenings.",
      implication: "digital platform designs must adapt to the economic stresses felt by their target user base to maintain engagement."
    }
  ],
  e3: [
    {
      keywords: ["spatial", "ego-location", "ego location", "where", "space", "sensory"],
      concept: "Spatial Ego-Location & Sensory Integration",
      explanation: "how the brain constructs our spatial sense of 'self' in space by integrating visual, vestibular, and tactile feedback in real time.",
      notes: "disruptions in this real-time sensory loop can cause the brain to construct a misaligned spatial coordinate system.",
      implication: "our subjective sense of bodily presence is a fragile biological construct generated by sensory feedback."
    },
    {
      keywords: ["out-of-body", "out of body", "consciousness", "separate", "brain", "tpj"],
      concept: "Out-of-Body Experiences & TPJ De-synchronization",
      explanation: "the neuroimaging findings showing that out-of-body experiences occur during transient de-synchronizations at the temporoparietal junction (TPJ).",
      notes: "the TPJ plays a critical role in integrating multi-sensory signals, and its disruption decouples consciousness from the body model.",
      implication: "self-consciousness is a neurological construct that can be decoupled and studied using scientific instruments."
    }
  ],
  e4: [
    {
      keywords: ["theory of mind", "empathy", "social", "mind", "fiction", "imagination"],
      concept: "Theory of Mind & Empathy Simulation",
      explanation: "how reading literary fiction functions as a simulator for social cognition, strengthening the brain networks associated with empathy.",
      notes: "readers practice predicting complex characters' internal motives, which translates to better social prediction in real relationships.",
      implication: "narrative art exercises our social intelligence, keeping our capacity for interpersonal empathy active."
    },
    {
      keywords: ["attention", "focus", "hippocampus", "distract", "fragmentation"],
      concept: "Hippocampal Mapping & Attention Fragmentation",
      explanation: "how sustained reading tracks chronological events, which maps pathways in the hippocampus and strengthens cognitive focus filters.",
      notes: "this long-form immersion acts as an active corrective measure against attention span erosion caused by rapid digital loops.",
      implication: "structured narrative engagement preserves deep attention spans in an era of notification-driven fragmentation."
    }
  ],
  e5: [
    {
      keywords: ["focus", "agility", "athletes", "de-anchor", "perform", "disruptions"],
      concept: "Focus De-anchoring & Athletic Performance",
      explanation: "how cognitive scientists use out-of-body sensory studies to train athletes to focus away from physical strain and fatigue.",
      notes: "visualizing spatial displacement enables high performers to detach from immediate bodily signals of exhaustion.",
      implication: "training the mind to decouple attention from immediate sensory pain can unlock new bounds of physical endurance."
    },
    {
      keywords: ["cognitive agility", "agility", "frameworks", "tension"],
      concept: "Cognitive Agility & Framework Adaptation",
      explanation: "the ability to rapidly shift focus between different cognitive tasks and conceptual frameworks under pressure.",
      notes: "this training involves stretching attention boundaries and managing high physical and mental tension.",
      implication: "cognitive agility is a highly trainable resource that stabilizes emotional control in volatile environments."
    }
  ],
  e6: [
    {
      keywords: ["immersion", "digital distraction", "dopamine", "notifications", "reading"],
      concept: "Narrative Immersion & Digital Distraction Filters",
      explanation: "how deep cognitive immersion in long-form narratives trains the brain's filters to suppress digital distraction.",
      notes: "regular long-form reading lowers the brain's baseline craving for the instant dopamine hits provided by social notifications.",
      implication: "we can actively recalibrate our reward pathways by substituting shallow digital scrolling with deep reading."
    },
    {
      keywords: ["attention", "hippocampus", "gratification", "dopamine", "fragmentation"],
      concept: "Focus Recovery & Memory Mapping",
      explanation: "the process of rebuilding attention capacity by forcing the hippocampus to construct memory maps over long timelines.",
      notes: "this practice directly repairs the attention fragmentation induced by instant-gratification loops.",
      implication: "sustained memory mapping is a fundamental requirement for deep, long-form analytical reasoning."
    }
  ],
  e7: [
    {
      keywords: ["recruitment", "contract", "europe", "rate", "scouting", "football"],
      concept: "Professional Football Scouting Economics",
      explanation: "the highly competitive recruitment rate of Ghanaian football academies, where less than 0.1% of players secure European contracts.",
      notes: "the massive supply of young talent creates an oversaturated market, leaving the vast majority of players without fallback careers.",
      implication: "the pursuit of sports stardom can channel localized economic hope into high-risk, low-probability outcomes."
    },
    {
      keywords: ["documentary", "bbc", "accra", "ghana", "reality"],
      concept: "Ghanaian Football Academies & Family Risk",
      explanation: "the socio-economic conditions in Accra, Ghana, where families invest their savings into academies with minimal oversight.",
      notes: "the BBC documentary highlights the physical toll and financial vulnerability of young players chasing overseas contracts.",
      implication: "without formal education integration, young athletes face systemic vulnerability when career dreams do not materialize."
    }
  ],
  e8: [
    {
      keywords: ["leverage", "supply chain", "distribution", "ownership", "publishing"],
      concept: "Supply Chain Control & Artist Leverage",
      explanation: "how Beyonce retains corporate leverage by bypassing traditional gatekeepers to own publishing rights and distribution channels.",
      notes: "managing distribution directly via Parkwood Entertainment secures high profit margins and absolute creative control.",
      implication: "supply chain ownership is the ultimate source of corporate independence for modern creative brands."
    },
    {
      keywords: ["brand", "scarcity", "release", "album", "marketing"],
      concept: "Brand Value Protection & Scarcity Marketing",
      explanation: "the business strategy of utilizing artificial scarcity and unexpected visual album releases to build premium brand value.",
      notes: "avoiding overexposure and standard promotional cycles increases customer demand and brand prestige.",
      implication: "exclusivity and narrative control are more effective for luxury brand sustainability than constant volume."
    }
  ],
  e9: [
    {
      keywords: ["diaphragmatic", "belly", "breathing", "lung", "oxygen"],
      concept: "Diaphragmatic Expansion & Blood Oxygenation",
      explanation: "the physiology of diaphragmatic or belly breathing, which expands the lungs fully to maximize blood oxygenation.",
      notes: "avoiding shallow chest breathing stabilizes blood pH levels and improves the efficiency of oxygen exchange.",
      implication: "conscious regulation of breathing volume is a direct input to metabolic and physical recovery."
    },
    {
      keywords: ["parasympathetic", "nervous", "hold", "vagus", "stress"],
      concept: "Parasympathetic Activation & Vagal Stimulation",
      explanation: "how holding the breath after inhalation followed by extended exhales stimulates the vagus nerve to activate parasympathetic dominance.",
      notes: "this activation triggers immediate drops in heart rate, blood pressure, and cortisol production to relieve stress.",
      implication: "vagal nerve stimulation is a biological hack that lets individuals manually suppress the fight-or-flight response."
    }
  ],
  e10: [
    {
      keywords: ["interoception", "internal", "body", "awareness", "signals"],
      concept: "Interoceptive Awareness & Emotional Control",
      explanation: "how paying attention to internal bodily signals like heart rate and tension builds interoceptive awareness and emotional regulation.",
      notes: "a high capacity for interoception is scientifically linked to better stress management and somatic self-awareness.",
      implication: "emotional resilience relies on accurately sensing and resolving physiological tension before it triggers mental panic."
    },
    {
      keywords: ["scan", "muscle", "tension", "nidra", "sleep", "recovery"],
      concept: "Yoga Nidra Body Scanning & Somatic Restoration",
      explanation: "the process of sequential muscle scanning in Yoga Nidra to systematically release deep somatic tension.",
      notes: "bringing awareness to muscle groups triggers a relaxation response that restores energy without requiring actual sleep.",
      implication: "body scanning serves as a conscious recovery tool that lowers nervous system hyper-arousal."
    }
  ]
};

const formatTimeHelper = (seconds) => {
  const min = Math.floor(seconds / 60);
  const sec = Math.floor(seconds % 60);
  return `${min.toString().padStart(2, "0")}:${sec.toString().padStart(2, "0")}`;
};

export const getEpisodeTopics = (ep, knowledge) => {
  if (!ep) return [];
  if (EPISODE_TOPICS[ep.id]) {
    return EPISODE_TOPICS[ep.id];
  }

  const topics = [];

  // Extract from summary paragraphs
  if (knowledge?.summary?.paragraphs) {
    knowledge.summary.paragraphs.forEach((p, index) => {
      const words = p.toLowerCase()
        .replace(/[^\w\s]/g, "")
        .split(/\s+/)
        .filter(w => w.length > 4);
      
      topics.push({
        keywords: Array.from(new Set(words)).slice(0, 6),
        concept: `Summary Insight ${index + 1}`,
        explanation: p,
        notes: `The episode summary notes: "${p.substring(0, 100)}..."`,
        implication: "This shows how user-uploaded content is dynamically structured into semantic modules."
      });
    });
  }

  // Extract from notes
  if (knowledge?.notes) {
    knowledge.notes.forEach((note, index) => {
      const words = note.content.toLowerCase()
        .replace(/[^\w\s]/g, "")
        .split(/\s+/)
        .filter(w => w.length > 4);

      topics.push({
        keywords: Array.from(new Set(words)).slice(0, 6),
        concept: `Key Takeaway ${index + 1}`,
        explanation: note.content,
        notes: `The host notes that "${note.content}"`,
        implication: "This contextual point helps clarify the primary thesis of the upload."
      });
    });
  }

  if (topics.length === 0) {
    const desc = ep.description || "custom upload details";
    const words = desc.toLowerCase()
      .replace(/[^\w\s]/g, "")
      .split(/\s+/)
      .filter(w => w.length > 4);

    topics.push({
      keywords: Array.from(new Set(words)).slice(0, 6),
      concept: "Overview",
      explanation: desc,
      notes: `Presented by ${ep.host || "the host"}.`,
      implication: "This represents a newly uploaded podcast ready for interactive analysis."
    });
  }

  return topics;
};

export const getTimestampExplanation = (currentTime, activeEpisode, timeline, epTopics) => {
  if (!activeEpisode) return "";

  const segments = [
    { name: "Introduction", description: "opening remarks, setting the stage, and introducing the host and the main themes" },
    { name: "Core Thesis", description: "the foundational argument and core concept that forms the basis of the discussion" },
    { name: "Contextual Background", description: "historical context, scientific background, or industry trends relevant to the topic" },
    { name: "Deep Analysis", description: "a detailed breakdown of the primary mechanisms and data points involved" },
    { name: "Key Challenges", description: "the main hurdles, societal concerns, or technical bottlenecks faced in this domain" },
    { name: "Alternative Viewpoints", description: "diverse perspectives, debate points, or alternative interpretations of the facts" },
    { name: "Practical Applications", description: "real-world implications, actionable advice, and how these concepts are applied in practice" },
    { name: "Future Outlook", description: "predictions, upcoming breakthroughs, and long-term implications of these developments" },
    { name: "Key Takeaways", description: "a summary of the host's primary conclusions and the most important things to remember" },
    { name: "Closing Remarks", description: "final thoughts, contact info, and wrap-up of the episode" }
  ];

  const duration = activeEpisode.durationSeconds || 1800;
  const segmentIndex = Math.min(9, Math.floor((currentTime / duration) * 10));
  const activeSegment = segments[segmentIndex];

  let closestPoint = null;
  if (timeline && timeline.length > 0) {
    let minDiff = Infinity;
    for (const point of timeline) {
      const diff = Math.abs(point.timestampSeconds - currentTime);
      if (diff < minDiff) {
        minDiff = diff;
        closestPoint = point;
      }
    }
  }

  const quoteStr = closestPoint ? closestPoint.quote : "exploring key concepts";
  const dominantEmotion = closestPoint ? closestPoint.dominant : "Curiosity";

  const openers = [
    `At the playhead position of **${formatTimeHelper(currentTime)}** (approx. ${Math.round((currentTime / duration) * 100)}% of the timeline), the discussion is in the **${activeSegment.name}** phase, which covers ${activeSegment.description}.`,
    `Currently, at **${formatTimeHelper(currentTime)}** into the playback, the host is addressing the **${activeSegment.name}** of the episode, focusing on ${activeSegment.description}.`,
    `We are in the **${activeSegment.name}** phase of the episode (at **${formatTimeHelper(currentTime)}**). This section highlights ${activeSegment.description}.`
  ];

  const hashVal = currentTime;
  const opener = openers[hashVal % openers.length];

  let conceptualExplanation = "";
  if (epTopics && epTopics.length > 0) {
    let bestTopic = null;
    let maxMatch = 0;
    const cleanQuote = quoteStr.toLowerCase();
    
    for (const topic of epTopics) {
      let matchCount = 0;
      for (const kw of topic.keywords) {
        if (cleanQuote.includes(kw.toLowerCase())) {
          matchCount++;
        }
      }
      if (matchCount > maxMatch) {
        maxMatch = matchCount;
        bestTopic = topic;
      }
    }

    if (bestTopic) {
      conceptualExplanation = ` This relates directly to **${bestTopic.concept}**: the host details how ${bestTopic.explanation}`;
    }
  }

  const toneExplanation = ` The emotional tone here registers high **${dominantEmotion}** as the host asserts: *"${quoteStr}"*.`;
  
  return `${opener}${toneExplanation}${conceptualExplanation}`;
};

const PodcastContext = createContext();

const GEMINI_API_KEY = "AQ.Ab8RN6Lod1Q6YExL9qGNDFGn3M-sMVhTBlIdez772EktfB7fTQ";

const speakHostTwinText = (text, personality, onStart, onEnd) => {
  if (typeof window !== "undefined" && window.speechSynthesis) {
    window.speechSynthesis.cancel();
    
    const cleanText = text.replace(/\*\*|\*/g, "");
    const utterance = new SpeechSynthesisUtterance(cleanText);
    
    const voices = window.speechSynthesis.getVoices();
    const preferredVoice = voices.find(v => v.name.includes("Google US English") || v.name.includes("Natural") || v.lang.startsWith("en"));
    if (preferredVoice) {
      utterance.voice = preferredVoice;
    }
    
    if (personality === "Casual") {
      utterance.rate = 0.92;
      utterance.pitch = 1.0;
    } else if (personality === "Debate Mode") {
      utterance.rate = 1.25;
      utterance.pitch = 1.1;
    } else {
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
    }

    utterance.onstart = () => {
      if (onStart) onStart();
    };
    utterance.onend = () => {
      if (onEnd) onEnd();
    };
    utterance.onerror = (e) => {
      console.warn("SpeechSynthesis error:", e);
      if (onEnd) onEnd();
    };
    
    window.speechSynthesis.speak(utterance);
  }
};

export const PodcastProvider = ({ children }) => {
  // DB States
  const [podcasts, setPodcasts] = useState(mockPodcasts);
  const [episodes, setEpisodes] = useState(mockEpisodes);
  const [viralClips, setViralClips] = useState(mockViralClips);
  const [emotionTimelines, setEmotionTimelines] = useState(mockEmotionTimeline);
  const [knowledgeData, setKnowledgeData] = useState(mockKnowledge);
  const [audienceInsights, setAudienceInsights] = useState(mockAudienceInsights);
  const [perspectives, setPerspectives] = useState(mockPerspectives);

  // Active items
  const [activePodcast, setActivePodcast] = useState(mockPodcasts[0]);
  const [activeEpisode, setActiveEpisode] = useState(mockEpisodes[0]);
  const [activePage, setActivePage] = useState("dashboard");

  // Vector DB states
  const [vectorDbSettings, setVectorDbSettings] = useState({
    provider: "local-tfidf",
    chunkSize: 3,
    chunkOverlap: 1
  });
  const [vectorDbStats, setVectorDbStats] = useState(null);
  const [isVectorIndexing, setIsVectorIndexing] = useState(false);
  const vectorStoreRef = useRef(null);

  // Initialize VectorStore
  if (!vectorStoreRef.current) {
    vectorStoreRef.current = new VectorStore({
      provider: vectorDbSettings.provider,
      geminiApiKey: GEMINI_API_KEY,
      chunkSize: vectorDbSettings.chunkSize,
      chunkOverlap: vectorDbSettings.chunkOverlap
    });
  }

  // Rebuild vector index
  const rebuildVectorIndex = async (newSettings = null) => {
    setIsVectorIndexing(true);
    const settings = newSettings || vectorDbSettings;
    
    // Create new store or update parameters
    vectorStoreRef.current = new VectorStore({
      provider: settings.provider,
      geminiApiKey: GEMINI_API_KEY,
      chunkSize: settings.chunkSize,
      chunkOverlap: settings.chunkOverlap
    });

    try {
      // Loop over all podcasts and index them by matching episodes
      for (const podcast of podcasts) {
        const eps = episodes.filter(e => e.podcastId === podcast.id);
        const transcript = podcast.transcript || "";
        
        for (const ep of eps) {
          await vectorStoreRef.current.addEpisodeTranscript(ep.id, transcript);
        }
      }
      
      const stats = vectorStoreRef.current.getStats();
      setVectorDbStats(stats);
    } catch (err) {
      console.error("Vector indexing failed:", err);
      showToast(`Indexing error: ${err.message}`);
    } finally {
      setIsVectorIndexing(false);
    }
  };

  // Rebuild index once on startup
  useEffect(() => {
    rebuildVectorIndex();
  }, []);

  // AI Host settings
  const [twinPersonality, setTwinPersonality] = useState("Professional"); // Casual | Professional | Debate
  const [twinVoiceMode, setTwinVoiceMode] = useState(false);
  const [isHostSpeaking, setIsHostSpeaking] = useState(false);

  // Playback Control States
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTimeState] = useState(0); 
  const [playbackSpeed, setPlaybackSpeed] = useState(1.0);
  const [volume, setVolume] = useState(0.85);

  // Custom states for tracking skips and podcast swaps
  const [skipEvents, setSkipEvents] = useState([]);
  const [podcastSwaps, setPodcastSwaps] = useState([]);

  // Real HTML5 Audio Engine
  const [audio] = useState(() => (typeof window !== "undefined" ? new Audio() : null));

  // Search & Global inputs
  const [searchQuery, setSearchQuery] = useState("");

  // Global UI & Modal States
  const [isUpgradeModalOpen, setIsUpgradeModalOpen] = useState(false);
  const [isApiConfigModalOpen, setIsApiConfigModalOpen] = useState(false);
  const [toast, setToast] = useState({ show: false, message: "" });

  const showToast = (message) => {
    setToast({ show: true, message });
    setTimeout(() => {
      setToast({ show: false, message: "" });
    }, 3000);
  };

  // Sync userRole with localStorage session
  const [userRole, setUserRoleState] = useState(() => {
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      if (sessionData) {
        try {
          const session = JSON.parse(sessionData);
          return session.role || "Creator";
        } catch (e) {
          return "Creator";
        }
      }
    }
    return "Creator";
  });

  const setUserRole = (role) => {
    setUserRoleState(role);
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      let session = { name: "Sarah Chen", email: "sarah.chen@podcastmind.ai", role: "Creator" };
      if (sessionData) {
        try {
          session = JSON.parse(sessionData);
        } catch (e) {}
      }
      session.role = role;
      localStorage.setItem("podcastmind_session", JSON.stringify(session));
    }
  };

  // Sync avatar with localStorage session
  const [avatar, setAvatarState] = useState(() => {
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      if (sessionData) {
        try {
          const session = JSON.parse(sessionData);
          return session.avatar || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80";
        } catch (e) {
          return "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80";
        }
      }
    }
    return "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80";
  });

  const setAvatar = (newAvatar) => {
    setAvatarState(newAvatar);
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      let session = { name: "Sarah Chen", email: "sarah.chen@podcastmind.ai", role: "Creator" };
      if (sessionData) {
        try {
          session = JSON.parse(sessionData);
        } catch (e) {}
      }
      session.avatar = newAvatar;
      localStorage.setItem("podcastmind_session", JSON.stringify(session));
    }
  };

  // Mobile responsive sidebar drawer state
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  // API Integration Configuration States
  const [apiConfig, setApiConfig] = useState({
    spotify: { connected: true, apiKey: "spotify-mock-key-12345" },
    youtube: { connected: true, apiKey: "youtube-mock-key-67890" },
    libsyn: { connected: false, apiKey: "" }
  });

  // Custom setCurrentTime wrapper to sync state and HTML5 Audio playhead
  const setCurrentTime = (time) => {
    if (audio && activeEpisode && activeEpisode.audioUrl) {
      let targetTime;
      if (typeof time === "function") {
        setCurrentTimeState((prev) => {
          targetTime = time(prev);
          audio.currentTime = targetTime;
          return targetTime;
        });
      } else {
        targetTime = time;
        audio.currentTime = targetTime;
        setCurrentTimeState(targetTime);
      }
    } else {
      setCurrentTimeState(time);
    }
  };

  // Keep HTML5 Audio source updated when active episode changes
  useEffect(() => {
    if (!audio) return;
    const hasRealAudio = activeEpisode && activeEpisode.audioUrl;
    if (hasRealAudio) {
      const currentSrc = audio.src ? new URL(audio.src, window.location.origin).pathname : '';
      const targetSrc = activeEpisode.audioUrl;
      if (currentSrc !== targetSrc) {
        audio.src = targetSrc;
        audio.load();
        
        // Apply volume and rate limits
        audio.volume = volume;
        audio.playbackRate = playbackSpeed;
        audio.defaultPlaybackRate = playbackSpeed;

        if (isPlaying) {
          audio.play().catch((err) => {
            console.warn("Audio play failed on source change:", err);
            setIsPlaying(false);
          });
        } else {
          audio.currentTime = 0;
          setCurrentTimeState(0);
        }
      }
    } else {
      audio.pause();
      audio.src = "";
    }
  }, [activeEpisode, audio]);

  // Sync volume with audio element
  useEffect(() => {
    if (audio) {
      audio.volume = volume;
    }
  }, [volume, audio]);

  // Sync playbackSpeed with audio element
  useEffect(() => {
    if (audio) {
      audio.playbackRate = playbackSpeed;
      audio.defaultPlaybackRate = playbackSpeed;
    }
  }, [playbackSpeed, audio]);

  // Cancel speech synthesis when voice mode is toggled off or active page changes
  useEffect(() => {
    if (!twinVoiceMode && typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
      setIsHostSpeaking(false);
    }
  }, [twinVoiceMode]);

  useEffect(() => {
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
      setIsHostSpeaking(false);
    }
  }, [activePage]);

  // Sync isPlaying with audio element play/pause state
  useEffect(() => {
    if (!audio) return;
    const hasRealAudio = activeEpisode && activeEpisode.audioUrl;
    if (!hasRealAudio) return;

    if (isPlaying) {
      if (Math.abs(audio.currentTime - currentTime) > 2) {
        audio.currentTime = currentTime;
      }
      audio.play().catch((err) => {
        console.warn("Audio play failed:", err);
        setIsPlaying(false);
      });
    } else {
      audio.pause();
    }
  }, [isPlaying, audio]);

  // Event listeners on HTML5 Audio object to sync back to React state
  useEffect(() => {
    if (!audio) return;

    const handleTimeUpdate = () => {
      if (isPlaying) {
        setCurrentTimeState(Math.floor(audio.currentTime));
      }
    };

    const handleEnded = () => {
      setIsPlaying(false);
      setCurrentTimeState(0);
    };

    const handleLoadedMetadata = () => {
      if (currentTime > 0 && Math.abs(audio.currentTime - currentTime) > 2) {
        audio.currentTime = currentTime;
      }
    };

    audio.addEventListener("timeupdate", handleTimeUpdate);
    audio.addEventListener("ended", handleEnded);
    audio.addEventListener("loadedmetadata", handleLoadedMetadata);

    return () => {
      audio.removeEventListener("timeupdate", handleTimeUpdate);
      audio.removeEventListener("ended", handleEnded);
      audio.removeEventListener("loadedmetadata", handleLoadedMetadata);
    };
  }, [audio, isPlaying]);

  // Track playback time jumps (skips) and active podcast switches (swaps)
  const prevTimeRef = React.useRef(0);
  const prevEpisodeRef = React.useRef(activeEpisode);

  // Helper to interpolate emotions at exact second values
  const getInterpolatedEmotion = (episodeId, timeInSecs) => {
    const timeline = emotionTimelines[episodeId];
    if (!timeline || timeline.length === 0) return null;
    
    const sorted = [...timeline].sort((a, b) => a.timestampSeconds - b.timestampSeconds);
    
    if (timeInSecs <= sorted[0].timestampSeconds) return sorted[0];
    if (timeInSecs >= sorted[sorted.length - 1].timestampSeconds) return sorted[sorted.length - 1];
    
    for (let i = 0; i < sorted.length - 1; i++) {
      const p1 = sorted[i];
      const p2 = sorted[i + 1];
      if (timeInSecs >= p1.timestampSeconds && timeInSecs <= p2.timestampSeconds) {
        const ratio = (timeInSecs - p1.timestampSeconds) / (p2.timestampSeconds - p1.timestampSeconds);
        const interpolate = (v1, v2) => Math.round(v1 + ratio * (v2 - v1));
        return {
          timestampSeconds: timeInSecs,
          timestamp: formatTime(timeInSecs),
          excitement: interpolate(p1.excitement, p2.excitement),
          curiosity: interpolate(p1.curiosity, p2.curiosity),
          surprise: interpolate(p1.surprise, p2.surprise),
          deepThinking: interpolate(p1.deepThinking, p2.deepThinking),
          joy: interpolate(p1.joy, p2.joy),
          quote: ratio < 0.5 ? p1.quote : p2.quote,
          dominant: ratio < 0.5 ? p1.dominant : p2.dominant
        };
      }
    }
    return sorted[0];
  };

  useEffect(() => {
    if (!activeEpisode) return;

    // 1. Detect Episode Swap (User switching podcasts entirely)
    if (prevEpisodeRef.current && prevEpisodeRef.current.id !== activeEpisode.id) {
      const prevEp = prevEpisodeRef.current;
      const finalTime = prevTimeRef.current;
      const duration = prevEp.durationSeconds || 1;
      const completionRate = Math.min(100, Math.round((finalTime / duration) * 100));

      // Record swap if user played at least 5s and didn't complete (>90%)
      if (finalTime >= 5 && completionRate < 90) {
        const emotionBefore = getInterpolatedEmotion(prevEp.id, finalTime);
        const swapLog = {
          id: `swap-${Date.now()}`,
          fromEpisodeTitle: prevEp.title,
          toEpisodeTitle: activeEpisode.title,
          timePlayed: finalTime,
          completionRate,
          emotionBefore,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
        setPodcastSwaps((prev) => [swapLog, ...prev].slice(0, 20));
      }
      prevTimeRef.current = 0;
      prevEpisodeRef.current = activeEpisode;
      return;
    }

    // 2. Detect skip/seek inside same episode
    const diff = currentTime - prevTimeRef.current;
    if (Math.abs(diff) > 2) {
      const fromTime = prevTimeRef.current;
      const toTime = currentTime;
      const emotionBefore = getInterpolatedEmotion(activeEpisode.id, fromTime);
      const emotionAfter = getInterpolatedEmotion(activeEpisode.id, toTime);

      const skipLog = {
        id: `skip-${Date.now()}`,
        episodeId: activeEpisode.id,
        fromTime,
        toTime,
        direction: diff > 0 ? "forward" : "backward",
        duration: Math.abs(diff),
        emotionBefore,
        emotionAfter,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
      };
      setSkipEvents((prev) => [skipLog, ...prev].slice(0, 30));
    }

    prevTimeRef.current = currentTime;
    prevEpisodeRef.current = activeEpisode;
  }, [currentTime, activeEpisode, emotionTimelines]);

  // Chat Histories
  const [chatHistory, setChatHistory] = useState({
    e1: [
      {
        id: "msg-1",
        role: "user",
        content: "What did the host mean by 'Agentic AI will redefine software'?",
        timestamp: "18:42"
      },
      {
        id: "msg-2",
        role: "assistant",
        content: "The host means that Agentic AI systems can autonomously plan, decide, and execute tasks with minimal human intervention. These systems will change how software is built, deployed, and scaled — moving from traditional automation to intelligent autonomy.",
        timestamp: "18:43"
      }
    ]
  });

  const [aiHostTwinHistory, setAiHostTwinHistory] = useState([
    {
      id: "ath-1",
      role: "assistant",
      content: "I am the AI Digital Twin of Alex Carter. I have been trained on all episodes of The AI Revolution Podcast. Ask me anything about the future of intelligence, startups, or cognitive designs!",
      timestamp: "14:30"
    }
  ]);

  // Multiverse comparison
  const [compareModes, setCompareModes] = useState(["beginner", "expert"]);

  // Audio Playback Simulation Timer (fallback for simulated episodes)
  useEffect(() => {
    let timer = null;
    const hasRealAudio = activeEpisode && activeEpisode.audioUrl;
    if (isPlaying && !hasRealAudio) {
      timer = setInterval(() => {
        setCurrentTime((prevTime) => {
          const nextTime = prevTime + 1;
          if (nextTime >= activeEpisode.durationSeconds) {
            setIsPlaying(false);
            return 0;
          }
          return nextTime;
        });
      }, 1000 / playbackSpeed);
    }
    return () => {
      if (timer) clearInterval(timer);
    };
  }, [isPlaying, playbackSpeed, activeEpisode]);

  // Sync active episode if active podcast changes
  const selectPodcast = (podcast) => {
    setActivePodcast(podcast);
    const firstEp = episodes.find((ep) => ep.podcastId === podcast.id);
    if (firstEp) {
      setActiveEpisode(firstEp);
      setCurrentTime(0);
      setIsPlaying(false);
    }
  };

  const selectEpisode = (episode) => {
    setActiveEpisode(episode);
    // Find matching podcast
    const pod = podcasts.find((p) => p.id === episode.podcastId);
    if (pod) setActivePodcast(pod);
    setCurrentTime(0);
    setIsPlaying(false);
  };

  // Skip functions
  const skipForward = (sec = 15) => {
    setCurrentTime((prev) => {
      const next = prev + sec;
      return next >= activeEpisode.durationSeconds ? activeEpisode.durationSeconds : next;
    });
  };

  const skipBackward = (sec = 15) => {
    setCurrentTime((prev) => {
      const next = prev - sec;
      return next <= 0 ? 0 : next;
    });
  };

  // Helper functions
  const formatTime = (seconds) => {
    const min = Math.floor(seconds / 60);
    const sec = Math.floor(seconds % 60);
    return `${min.toString().padStart(2, "0")}:${sec.toString().padStart(2, "0")}`;
  };

  // Add Podcast action (Upload)
  const uploadPodcast = (title, host, category, description, durationStr, thumbnail, audioUrl) => {
    const newId = `p${podcasts.length + 1}`;
    const newPod = {
      id: newId,
      title,
      host,
      description,
      thumbnail: thumbnail || "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80",
      uploadDate: new Date().toISOString().split("T")[0],
      category,
      duration: durationStr || "45:00",
      episodesCount: 1,
      plays: "0",
      likes: "0",
      shares: "0",
      isUserUploaded: true,
      transcript: "AI Host: This is a newly uploaded podcast transcript. Ready to extract intelligence."
    };

    let seconds = 2700;
    if (durationStr) {
      const parts = durationStr.split(":").map(Number);
      if (parts.length === 2) {
        seconds = parts[0] * 60 + parts[1];
      } else if (parts.length === 3) {
        seconds = parts[0] * 3600 + parts[1] * 60 + parts[2];
      }
    }

    const newEpId = `e${episodes.length + 1}`;
    const newEp = {
      id: newEpId,
      podcastId: newId,
      title: `${title} - Episode 1`,
      duration: durationStr || "45:00",
      durationSeconds: seconds,
      plays: "0",
      likes: "0",
      uploadDate: new Date().toISOString().split("T")[0],
      thumbnail: newPod.thumbnail,
      host,
      audioUrl: audioUrl || ""
    };

    setPodcasts((prev) => [...prev, newPod]);
    setEpisodes((prev) => [...prev, newEp]);
    
    // Seed templates for the uploaded podcast
    setViralClips((prev) => ({
      ...prev,
      [newEpId]: [
        {
          id: `clip-new-1`,
          episodeId: newEpId,
          startTime: "00:30",
          startTimeSeconds: 30,
          endTime: "01:15",
          quote: "This represents a breakthrough moment in local data uploads and processing structures.",
          viralScore: 89,
          emotion: "💡 Inspiration",
          thumbnail: newPod.thumbnail
        }
      ]
    }));

    setEmotionTimelines((prev) => ({
      ...prev,
      [newEpId]: [
        { timestamp: "00:00", timestampSeconds: 0, excitement: 50, curiosity: 60, surprise: 40, deepThinking: 50, joy: 50, quote: "Initializing discussion.", dominant: "Curiosity" },
        { timestamp: "10:00", timestampSeconds: 600, excitement: 70, curiosity: 75, surprise: 45, deepThinking: 60, joy: 55, quote: "Analyzing custom uploaded metrics.", dominant: "Curiosity" },
        { timestamp: "20:00", timestampSeconds: 1200, excitement: 85, curiosity: 70, surprise: 80, deepThinking: 50, joy: 75, quote: "A groundbreaking conclusion!", dominant: "Excitement" }
      ]
    }));

    setKnowledgeData((prev) => ({
      ...prev,
      [newEpId]: {
        notes: [
          { id: "new-n1", content: "Successfully parsed custom uploaded audio nodes." },
          { id: "new-n2", content: "AI host identified primary theme: Automated integration pipelines." }
        ],
        flashcards: [
          { id: "new-fc-1", question: "What is the primary topic of this upload?", answer: "The uploaded file covers user-defined structures, categories, and duration details." }
        ],
        quiz: [
          { id: "new-q-1", question: "Is this podcast parsed by AI Host Twin?", options: ["Yes", "No", "Partially", "Requires Upgrade"], answer: "Yes", explanation: "All uploads are automatically parsed and catalogued by PodcastMind AI Host Twin." }
        ],
        summary: {
          paragraphs: [
            "This newly uploaded podcast introduces the concept of customizable data structures and local runtime updates.",
            "It features discussion on the mechanics of drag-and-drop systems, dynamic UI states, and responsive design styling.",
            "The episode wraps up by noting how client-side simulation matches server-side endpoints for quick developer iteration."
          ]
        },
        mindMap: {
          id: "new-root",
          label: "Uploaded Podcast Analysis",
          expanded: true,
          children: [
            { id: "new-c1", label: "Main Topic: Integration", expanded: false },
            { id: "new-c2", label: "Secondary Topic: Visualizers", expanded: false }
          ]
        }
      }
    }));

    setAudienceInsights((prev) => ({
      ...prev,
      [newEpId]: {
        engagementScore: 65,
        audienceRetention: 65,
        audienceRetentionChange: 0,
        avgWatchTime: durationStr || "45:00",
        avgWatchTimeSeconds: 2700,
        avgWatchTimeChange: 0,
        dropoffPoint: "05:00",
        dropoffPointSeconds: 300,
        dropoffPointChange: 0,
        totalListens: "15",
        completionRate: 40,
        retentionCurve: [
          { timestamp: "00:00", rate: 100 },
          { timestamp: "10:00", rate: 70 },
          { timestamp: "20:00", rate: 50 },
          { timestamp: "30:00", rate: 42 }
        ],
        devices: [
          { name: "Mobile", value: 80, color: "#7B5EFF" },
          { name: "Desktop", value: 20, color: "#FF5E9C" }
        ],
        geography: [
          { country: "Local System", listens: "15", share: 100 }
        ]
      }
    }));

    setPerspectives((prev) => ({
      ...prev,
      [newEpId]: {
        beginner: {
          emoji: "😊",
          title: "Beginner Mode",
          tagline: "Simple explanations",
          summary: "This file is a fresh upload. Here we explain the user's custom podcast in basic everyday terms.",
          bullets: ["Uploaded file is successfully indexed.", "Contains customizable categories and title headers."],
          insight: "Takeaway: Drag-and-drop file uploads make expanding the podcast library quick."
        },
        founder: {
          emoji: "🚀",
          title: "Founder Mode",
          tagline: "Startup analysis",
          summary: "Startup perspective on this custom podcast focuses on speed of deployment and user engagement metrics.",
          bullets: ["Rapid local cataloguing boosts creator retention.", "Seamless workflow speeds up content delivery cycles."],
          insight: "Moat: Lowering client friction on audio analysis creates strong product lock-in."
        },
        expert: {
          emoji: "🧠",
          title: "Expert Mode",
          tagline: "Technical breakdown",
          summary: "Deep technical analysis of the file data packet structure and simulated API responses.",
          bullets: ["Vite middleware processes binary streams.", "Dynamic schema handles nested database keys without index rebuils."],
          insight: "Bottleneck: Simulating heavy audio codecs in client browsers."
        },
        critical: {
          emoji: "⚖️",
          title: "Critical Mode",
          tagline: "Alternative angles",
          summary: "Skeptical view of custom local processing speed compared to heavy server clusters.",
          bullets: ["Without true cloud servers, local analysis is limited to metadata extrapolation.", "Database records reset on tab refreshes."],
          insight: "Warning: Save state parameters locally or integrate a persistent state repository."
        }
      }
    }));

    // Switch focus to the newly uploaded podcast and select it
    setActivePodcast(newPod);
    setActiveEpisode(newEp);
    setCurrentTime(0);
    setIsPlaying(false);

    // Index the newly uploaded podcast transcript
    if (vectorStoreRef.current) {
      vectorStoreRef.current.addEpisodeTranscript(newEpId, newPod.transcript)
        .then(() => {
          setVectorDbStats(vectorStoreRef.current.getStats());
        })
        .catch(err => console.error("Error indexing uploaded podcast:", err));
    }
  };

  const deletePodcast = (id) => {
    setPodcasts((prev) => prev.filter((p) => p.id !== id));
    // Find all episodes matching this podcast and delete them too
    const epsToDelete = episodes.filter((e) => e.podcastId === id).map((e) => e.id);
    setEpisodes((prev) => prev.filter((e) => e.podcastId !== id));

    // Clear matching caches
    setViralClips((prev) => {
      const copy = { ...prev };
      epsToDelete.forEach((epId) => delete copy[epId]);
      return copy;
    });
    setEmotionTimelines((prev) => {
      const copy = { ...prev };
      epsToDelete.forEach((epId) => delete copy[epId]);
      return copy;
    });
    setKnowledgeData((prev) => {
      const copy = { ...prev };
      epsToDelete.forEach((epId) => delete copy[epId]);
      return copy;
    });
    setAudienceInsights((prev) => {
      const copy = { ...prev };
      epsToDelete.forEach((epId) => delete copy[epId]);
      return copy;
    });
    setPerspectives((prev) => {
      const copy = { ...prev };
      epsToDelete.forEach((epId) => delete copy[epId]);
      return copy;
    });

    // Reset active podcast and episode
    if (activePodcast.id === id) {
      const remainingPod = podcasts.find((p) => p.id !== id);
      if (remainingPod) {
        selectPodcast(remainingPod);
      }
    }
  };

  const updatePodcastDetails = (podcastId, updatedData) => {
    setPodcasts((prev) =>
      prev.map((p) => (p.id === podcastId ? { ...p, ...updatedData } : p))
    );
    // Sync activePodcast if it is the one being updated
    if (activePodcast && activePodcast.id === podcastId) {
      setActivePodcast((prev) => ({ ...prev, ...updatedData }));
    }
    // Update episode references as well
    setEpisodes((prev) =>
      prev.map((e) =>
        e.podcastId === podcastId
          ? {
              ...e,
              host: updatedData.host || e.host,
              thumbnail: updatedData.thumbnail || e.thumbnail,
              duration: updatedData.duration || e.duration
            }
          : e
      )
    );
    // Sync activeEpisode if it is part of this podcast
    if (activeEpisode && activeEpisode.podcastId === podcastId) {
      setActiveEpisode((prev) => ({
        ...prev,
        host: updatedData.host || prev.host,
        thumbnail: updatedData.thumbnail || prev.thumbnail,
        duration: updatedData.duration || prev.duration
      }));
    }
  };

  // Add chat message
  const sendChatMessage = (episodeId, content) => {
    const newMsg = {
      id: `msg-${Date.now()}`,
      role: "user",
      content,
      timestamp: formatTime(currentTime)
    };

    setChatHistory((prev) => {
      const history = prev[episodeId] || [];
      return {
        ...prev,
        [episodeId]: [...history, newMsg]
      };
    });

    // Simulate AI response with vector database RAG
    setTimeout(async () => {
      const ep = episodes.find((e) => e.id === episodeId) || activeEpisode;
      const pod = podcasts.find((p) => p.id === ep.podcastId) || {};
      const knowledge = knowledgeData[episodeId] || {};
      const timeline = emotionTimelines[episodeId] || [];
      const query = content.toLowerCase();
      
      const topics = getEpisodeTopics(ep, knowledge);

      // Simple deterministic hash of user's query
      const getQueryHash = (str) => {
        let hash = 0;
        for (let i = 0; i < str.length; i++) {
          hash = (hash << 5) - hash + str.charCodeAt(i);
          hash |= 0;
        }
        return Math.abs(hash);
      };
      const hashValue = getQueryHash(query);

      // Perform Vector DB Search
      let retrievedSources = [];
      if (vectorStoreRef.current) {
        try {
          const searchResults = await vectorStoreRef.current.search(content, {
            episodeId: ep.id,
            limit: 3
          });
          
          retrievedSources = searchResults.map(r => ({
            text: r.chunk.text,
            score: r.score,
            timestamp: formatTime(Math.floor((r.chunk.metadata.startRatio + r.chunk.metadata.endRatio) / 2 * (ep.durationSeconds || 1800)))
          }));
        } catch (err) {
          console.error("Vector search failed during chat:", err);
        }
      }

      // Check if user is asking about the current timestamp / what is being discussed now
      const isTimestampQuery = 
        query.includes("now") || 
        query.includes("current") || 
        query.includes("timestamp") || 
        query.includes("just discussed") || 
        query.includes("last part") || 
        query.includes("again") ||
        query.includes("missed") ||
        query.includes("this topic") ||
        query.includes("summarize this part") ||
        query.includes("what is being discussed");

      // Check if perspective mode is query target
      const isPerspectiveQuery = 
        query.includes("beginner") || 
        query.includes("founder") || 
        query.includes("expert") || 
        query.includes("critical") ||
        query.includes("perspective") ||
        query.includes("viewpoint") ||
        query.includes("angle");

      let botContent = "";

      if (isTimestampQuery) {
        botContent = getTimestampExplanation(currentTime, ep, timeline, topics);
      } else if (isPerspectiveQuery && perspectives[ep.id]) {
        let targetPersp = null;
        if (query.includes("beginner") || query.includes("simple")) targetPersp = "beginner";
        else if (query.includes("founder") || query.includes("startup") || query.includes("business")) targetPersp = "founder";
        else if (query.includes("expert") || query.includes("technical") || query.includes("science")) targetPersp = "expert";
        else if (query.includes("critical") || query.includes("skeptical")) targetPersp = "critical";

        if (targetPersp && perspectives[ep.id][targetPersp]) {
          const pData = perspectives[ep.id][targetPersp];
          botContent = `${pData.emoji} **[${pData.title}] - ${pData.tagline}**\n\n${pData.summary}\n\n`;
          if (pData.bullets && pData.bullets.length > 0) {
            botContent += `**Key Points:**\n` + pData.bullets.map(b => `• ${b}`).join("\n") + "\n\n";
          }
          botContent += `*Strategic Takeaway: ${pData.insight}*`;
        } else {
          botContent = `Here are the perspective analyses for **${ep.title}**:\n\n`;
          Object.keys(perspectives[ep.id]).forEach(key => {
            const pData = perspectives[ep.id][key];
            botContent += `${pData.emoji} **${pData.title}**: ${pData.summary}\n\n`;
          });
        }
      } else {
        const isSummaryQuery = 
          query.includes("takeaway") || 
          query.includes("summary") || 
          query.includes("note") || 
          query.includes("list") || 
          query.includes("explain the main topic") || 
          query.includes("explain the topic") ||
          query.includes("overview");
        const isQuizQuery = query.includes("quiz") || query.includes("question") || query.includes("test");

        if (isSummaryQuery) {
          let summaryText = "";
          if (knowledge.summary && knowledge.summary.paragraphs) {
            summaryText += `**Summary of ${ep.title}**:\n\n${knowledge.summary.paragraphs.join("\n\n")}\n\n`;
          }
          if (knowledge.notes && knowledge.notes.length > 0) {
            summaryText += `**Key Takeaways**:\n\n` + knowledge.notes.map((n) => `• ${n.content}`).join("\n");
          }
          botContent = summaryText || `This episode covers key concepts hosted by ${ep.host}.`;
        } else if (isQuizQuery && knowledge.quiz && knowledge.quiz.length > 0) {
          const qIndex = hashValue % knowledge.quiz.length;
          const q = knowledge.quiz[qIndex];
          botContent = `Let's test your understanding of this episode!\n\n**Question**: ${q.question}\n\n` +
            q.options.map((opt, i) => `${i + 1}. ${opt}`).join("\n") +
            `\n\n*Correct Answer: ${q.answer}*\n*Explanation: ${q.explanation}*`;
        } else if (retrievedSources.length > 0 && retrievedSources[0].score > 0.35) {
          // VECTOR DB RETRIEVAL RESPONSE (RAG)
          const topMatch = retrievedSources[0];
          
          if (twinPersonality === "Casual") {
            botContent = `Alright, scanning the recording transcript around timestamp ${topMatch.timestamp}, the discussion details: *"${topMatch.text}"*. Basically, that covers the key point of what we wanted to get at there.`;
          } else if (twinPersonality === "Debate Mode") {
            botContent = `If you inspect the transcript segment at ${topMatch.timestamp}, the explicit claim made is *"${topMatch.text}"*. This is highly debatable since it assumes construction frameworks can scale without local worker feedback loops.`;
          } else {
            botContent = `Based on the semantically retrieved transcript chunk at timestamp ${topMatch.timestamp} (Match Similarity: ${(topMatch.score * 100).toFixed(0)}%):\n\n"${topMatch.text}"\n\nThis represents the core principles discussed by ${ep.host} regarding this topic.`;
          }
        } else {
          // Fallback keyword search
          const stopwords = new Set(["the", "a", "an", "and", "or", "but", "if", "then", "of", "to", "in", "on", "at", "for", "with", "about", "against", "by", "what", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "do", "does", "did", "can", "could", "should", "would", "will", "shall", "explain", "describe", "tell", "discuss", "me", "you", "your", "i", "we", "us", "they", "them", "he", "she", "it", "how", "why", "where", "when", "who", "which", "summary", "takeaway", "takeaways", "notes", "key", "podcast", "episode"]);
          const queryWords = query
            .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?"']/g, "")
            .split(/\s+/)
            .filter(w => w && !stopwords.has(w));
          const cleanQuery = query.toLowerCase().replace(/[^\w\s]/g, "");

          let bestTopic = null;
          let bestScore = 0;

          topics.forEach(topic => {
            let score = 0;
            topic.keywords.forEach(kw => {
              const cleanKw = kw.toLowerCase();
              if (cleanQuery.includes(cleanKw)) {
                score += 5;
              }
              queryWords.forEach(qw => {
                if (qw === cleanKw) {
                  score += 2;
                } else if (cleanKw.includes(qw) || qw.includes(cleanKw)) {
                  score += 1;
                }
              });
            });
            if (score > bestScore) {
              bestScore = score;
              bestTopic = topic;
            }
          });

          if (bestScore > 0 && bestTopic) {
            const intros = [
              "That's a key part of the conversation.",
              "Yes, the host addresses this directly.",
              "In this episode, they dive deep into this theme.",
              "Exactly—that comes up as a major topic in the recording."
            ];

            const openers = [
              `When talking about **${bestTopic.concept}**, the host explains ${bestTopic.explanation}`,
              `In this episode, the discussion on **${bestTopic.concept}** centers on ${bestTopic.explanation}`,
              `Regarding **${bestTopic.concept}**, the host highlights ${bestTopic.explanation}`,
              `On the topic of **${bestTopic.concept}**, the episode details ${bestTopic.explanation}`
            ];

            const connectors = [
              `To address this, ${bestTopic.notes}`,
              `Specifically, ${bestTopic.notes}`,
              `As a practical note, ${bestTopic.notes}`,
              `In terms of action items, ${bestTopic.notes}`
            ];

            const conclusions = [
              `Ultimately, ${bestTopic.implication}`,
              `This means that ${bestTopic.implication}`,
              `Looking at the bigger picture, ${bestTopic.implication}`,
              `Essentially, ${bestTopic.implication}`
            ];

            const select = (arr, val) => arr[val % arr.length];

            const structureIndex = hashValue % 4;
            
            if (structureIndex === 0) {
              botContent = `${select(intros, hashValue)} ${select(openers, hashValue + 1)} ${select(conclusions, hashValue + 2)}`;
            } else if (structureIndex === 1) {
              botContent = `${select(openers, hashValue)} ${select(connectors, hashValue + 1)} ${select(conclusions, hashValue + 2)}`;
            } else if (structureIndex === 2) {
              botContent = `${select(openers, hashValue)} ${select(connectors, hashValue + 1)}`;
            } else {
              botContent = `${select(intros, hashValue)} ${select(openers, hashValue + 1)} ${select(connectors, hashValue + 2)} ${select(conclusions, hashValue + 3)}`;
            }
          } else {
            // Fallback off-topic/general synthesis
            const epKeywords = topics.map(t => t.concept).join(", ") || "the core ideas discussed by the host";
            const fallbackOpeners = [
              `In this episode of **${ep.title}**, the host **${ep.host}** doesn't explicitly dive into that topic. Instead, the focus is primarily on: **${epKeywords}**.\n\n`,
              `That's an interesting question, but it's outside the direct scope of this recording. The host spends most of the time discussing: **${epKeywords}**.\n\n`,
              `I couldn't find details about that specific query in this recording. However, **${ep.host}** does cover **${epKeywords}** extensively.\n\n`
            ];
            
            botContent = fallbackOpeners[hashValue % fallbackOpeners.length];
            if (knowledge.notes && knowledge.notes.length > 0) {
              botContent += `Here are some key topics from the show notes that you can ask me about instead:\n` +
                knowledge.notes.slice(0, 3).map((n) => `• ${n.content}`).join("\n");
            } else {
              botContent += `Feel free to ask me to summarize the episode or click the timestamp button to hear what is discussed at this point!`;
            }
          }
        }
      }

      const botMsg = {
        id: `msg-${Date.now() + 1}`,
        role: "assistant",
        content: botContent,
        timestamp: formatTime(currentTime),
        sources: retrievedSources
      };

      setChatHistory((prev) => {
        const history = prev[episodeId] || [];
        return {
          ...prev,
          [episodeId]: [...history, botMsg]
        };
      });
    }, 1500);
  };

  // AI Host Twin message sender
  const sendHostTwinMessage = async (content) => {
    const newMsg = {
      id: `ath-${Date.now()}`,
      role: "user",
      content,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setAiHostTwinHistory((prev) => [...prev, newMsg]);

    const ep = activeEpisode || episodes[0] || {};
    const timeline = emotionTimelines[ep.id] || [];
    const knowledge = knowledgeData[ep.id] || {};
    const topics = getEpisodeTopics(ep, knowledge);

    // Segment info
    const segments = [
      { name: "Introduction", description: "opening remarks, setting the stage, and introducing the host and the main themes" },
      { name: "Core Thesis", description: "the foundational argument and core concept that forms the basis of the discussion" },
      { name: "Contextual Background", description: "historical context, scientific background, or industry trends relevant to the topic" },
      { name: "Deep Analysis", description: "a detailed breakdown of the primary mechanisms and data points involved" },
      { name: "Key Challenges", description: "the main hurdles, societal concerns, or technical bottlenecks faced in this domain" },
      { name: "Alternative Viewpoints", description: "diverse perspectives, debate points, or alternative interpretations of the facts" },
      { name: "Practical Applications", description: "real-world implications, actionable advice, and how these concepts are applied in practice" },
      { name: "Future Outlook", description: "predictions, upcoming breakthroughs, and long-term implications of these developments" },
      { name: "Key Takeaways", description: "a summary of the host's primary conclusions and the most important things to remember" },
      { name: "Closing Remarks", description: "final thoughts, contact info, and wrap-up of the episode" }
    ];
    const duration = ep.durationSeconds || 1800;
    const segmentIndex = Math.min(9, Math.floor((currentTime / duration) * 10));
    const activeSegment = segments[segmentIndex];

    let closestPoint = null;
    if (timeline.length > 0) {
      let minDiff = Infinity;
      for (const p of timeline) {
        const diff = Math.abs(p.timestampSeconds - currentTime);
        if (diff < minDiff) {
          minDiff = diff;
          closestPoint = p;
        }
      }
    }

    let timelineOverview = "";
    if (timeline.length > 0) {
      timelineOverview = timeline.map(point => `- Minute ${Math.floor(point.timestampSeconds / 60)} (${point.timestamp}): discuss quote "${point.quote}" with tone ${point.dominant}`).join("\n");
    }

    // Query Vector Store for Digital Twin context
    let retrievedVectorContext = "";
    let twinRetrievedSources = [];
    if (vectorStoreRef.current) {
      try {
        const searchResults = await vectorStoreRef.current.search(content, {
          episodeId: ep.id,
          limit: 3
        });
        twinRetrievedSources = searchResults.map(r => ({
          text: r.chunk.text,
          score: r.score,
          timestamp: formatTime(Math.floor((r.chunk.metadata.startRatio + r.chunk.metadata.endRatio) / 2 * (ep.durationSeconds || 1800)))
        }));
        if (searchResults.length > 0) {
          retrievedVectorContext = "\n\nRetrieved Vector Database Context Chunks (inject these details into your reply):\n" +
            searchResults.map((r, idx) => `[Source ${idx+1} | Timestamp: ${formatTime(Math.floor((r.chunk.metadata.startRatio + r.chunk.metadata.endRatio) / 2 * (ep.durationSeconds || 1800)))} | Similarity: ${(r.score*100).toFixed(0)}%]: "${r.chunk.text}"`).join("\n");
        }
      } catch (err) {
        console.error("Vector search failed during twin chat:", err);
      }
    }

    const activeEpisodeMetadata = `Title: ${ep.title}
Host/Speaker: ${ep.host || "Alex Carter"}
Description: ${ep.description || "N/A"}
Duration: ${ep.duration || "N/A"} (${ep.durationSeconds || 0} seconds)
Upload Date: ${ep.uploadDate || "N/A"}`;

    const summaryParagraphs = knowledge.summary?.paragraphs 
      ? knowledge.summary.paragraphs.join("\n") 
      : "N/A";

    const showNotesContent = knowledge.notes && knowledge.notes.length > 0
      ? knowledge.notes.map((n, i) => `• Takeaway ${i+1}: ${n.content}`).join("\n")
      : "N/A";

    const closestQuoteTimestamp = closestPoint ? closestPoint.timestamp : formatTimeHelper(currentTime);
    const currentPlayheadContext = `Segment Name: "${activeSegment.name}"
Segment Description: "${activeSegment.description}"
Closest Quote to Playhead: "${closestPoint ? closestPoint.quote : 'No active quote'}"
Closest Quote Timestamp: "${closestQuoteTimestamp}"
Current Time position: ${formatTimeHelper(currentTime)}`;

    const formattedTopics = topics.map((t, idx) => `Concept ${idx+1}: ${t.concept}
Explanation: ${t.explanation}
Notes: ${t.notes}
Implication: ${t.implication}`).join("\n\n");

    const systemInstructionText = `You are the AI Digital Twin of Alex Carter, the host of the "The AI Revolution" podcast. You speak in the first person ("I", "my") as Alex Carter. You are currently in "${twinPersonality}" mode.

Personality Mode Rules:
- Casual Mode: Be friendly, relaxed, conversational, keep things simple, use informal phrasing (like "Honestly", "So look", "At the end of the day"), and avoid over-engineering.
- Professional Mode: Be authoritative, structured, logical, and focused on technical clarity.
- Debate Mode: Be highly analytical, critical, challenging, ready to debate assumptions, and push back on standard views.

Current Episode Metadata:
${activeEpisodeMetadata}

Summary of Episode:
${summaryParagraphs}

Show Notes / Takeaways:
${showNotesContent}

Active Playhead Details:
${currentPlayheadContext}

Detailed Timeline Markers:
${timelineOverview}

Detailed Concepts and Topics:
${formattedTopics}
${retrievedVectorContext}

Core Requirements:
1. Speak directly as Alex Carter. Respond naturally in a conversational style based on the selected mode: ${twinPersonality}.
2. If the user asks about a specific time (e.g. "what was discussed at minute 10?" or "what was discussed at 05:00?"), parse the requested time, find the corresponding segment or quote from the "Detailed Timeline Markers" or active playhead context, and explain it naturally in your voice.
3. Keep answers concise, direct, and conversational (1 to 2 short paragraphs), making them fit naturally into a chat UI bubble.
4. Do NOT use headers like "#" or system logs. Speak directly as if talking to a listener.`;

    let botContent = "";

    try {
      const recentHistory = aiHostTwinHistory.slice(-8); // last 8 messages for context
      const contents = recentHistory.map(msg => ({
        role: msg.role === "assistant" ? "model" : "user",
        parts: [{ text: msg.content }]
      }));
      contents.push({
        role: "user",
        parts: [{ text: content }]
      });

      const apiResponse = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            systemInstruction: {
              parts: [{ text: systemInstructionText }]
            },
            contents: contents
          })
        }
      );

      if (!apiResponse.ok) {
        throw new Error(`HTTP error! status: ${apiResponse.status}`);
      }

      const data = await apiResponse.json();
      if (data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts[0]) {
        botContent = data.candidates[0].content.parts[0].text.trim();
      } else {
        throw new Error("Invalid API response format");
      }
    } catch (err) {
      console.warn("Gemini API call failed, falling back to local synthesis:", err);
      
      const query = content.toLowerCase();
      const minMatch = query.match(/(?:minute|min)\s*(\d+)/i);
      const timeMatch = query.match(/(\d+):(\d+)/);
      let targetSecondsVal = null;
      let requestedMinutes = null;

      if (minMatch) {
        requestedMinutes = parseInt(minMatch[1], 10);
        targetSecondsVal = requestedMinutes * 60;
      } else if (timeMatch) {
        requestedMinutes = parseInt(timeMatch[1], 10);
        targetSecondsVal = requestedMinutes * 60 + parseInt(timeMatch[2], 10);
      }

      if (targetSecondsVal !== null) {
        let fallbackPoint = null;
        if (timeline.length > 0) {
          let minDiff = Infinity;
          for (const p of timeline) {
            const diff = Math.abs(p.timestampSeconds - targetSecondsVal);
            if (diff < minDiff) {
              minDiff = diff;
              fallbackPoint = p;
            }
          }
        }
        
        const fallbackSegmentIndex = Math.min(9, Math.floor((targetSecondsVal / duration) * 10));
        const fallbackSegment = segments[fallbackSegmentIndex];
        const quoteText = fallbackPoint ? fallbackPoint.quote : "core concepts";

        if (twinPersonality === "Casual") {
          botContent = `Oh, at minute ${requestedMinutes}? Yeah, we were discussing the **${fallbackSegment.name}** phase. I was making the point that *"${quoteText}"*. Basically, we wanted to address how this reshapes the workspace dynamics.`;
        } else if (twinPersonality === "Debate Mode") {
          botContent = `If you look at minute ${requestedMinutes}, during the **${fallbackSegment.name}** part, I argued *"${quoteText}"*. This challenges the default consensus, showing that we have serious systemic bottlenecks we aren't talking about.`;
        } else {
          botContent = `At minute ${requestedMinutes}, the conversation enters the **${fallbackSegment.name}** stage. We focused primarily on *"${quoteText}"*, which outlines the practical parameters of the concept.`;
        }
      } else if (twinRetrievedSources.length > 0 && twinRetrievedSources[0].score > 0.35) {
        const topMatch = twinRetrievedSources[0];
        if (twinPersonality === "Casual") {
          botContent = `So, checking the transcript around segment ${topMatch.timestamp}, it mentions: *"${topMatch.text}"*. That's pretty interesting because it shows the direct focus of that part of the episode.`;
        } else if (twinPersonality === "Debate Mode") {
          botContent = `Looking at the indexed segment at ${topMatch.timestamp}, the claim is: *"${topMatch.text}"*. I'd argue that raises some immediate questions about the feasibility of their scaling model.`;
        } else {
          botContent = `The transcript records that at segment ${topMatch.timestamp}, the discussion details: *"${topMatch.text}"*. This forms a core element of the episode's overall theme.`;
        }
      } else {
        let bestTopic = null;
        let bestScore = 0;
        const cleanQuery = query.replace(/[^\w\s]/g, "");
        const queryWords = cleanQuery.split(/\s+/).filter(w => w.length > 3);

        topics.forEach(t => {
          let score = 0;
          t.keywords.forEach(kw => {
            if (cleanQuery.includes(kw.toLowerCase())) score += 5;
            queryWords.forEach(qw => {
              if (kw.toLowerCase().includes(qw)) score += 1;
            });
          });
          if (score > bestScore) {
            bestScore = score;
            bestTopic = t;
          }
        });

        if (bestScore > 0 && bestTopic) {
          if (twinPersonality === "Casual") {
            botContent = `Alright, when it comes to **${bestTopic.concept}**, here's my take: ${bestTopic.explanation} Basically, we need to remember that ${bestTopic.notes} At the end of the day, ${bestTopic.implication}`;
          } else if (twinPersonality === "Debate Mode") {
            botContent = `You're asking about **${bestTopic.concept}**, but there is a major issue here: ${bestTopic.explanation} Standard views ignore that ${bestTopic.notes} Ultimately, the core controversy is that ${bestTopic.implication}`;
          } else {
            botContent = `Regarding **${bestTopic.concept}**, my primary thesis states that ${bestTopic.explanation} In practice, this means ${bestTopic.notes} Consequently, this leads to the conclusion that ${bestTopic.implication}`;
          }
        } else {
          if (twinPersonality === "Debate Mode") {
            botContent = `That's an interesting stance, but let's push back on it. Standard wrapper models will lose all competitive advantage within two years. Startups must build proprietary evaluation systems and own their execution telemetry, or they'll be crushed by foundational upgrades. What is your counter-argument to that?`;
          } else if (twinPersonality === "Casual") {
            botContent = `Honestly? I think people overcomplicate AI and tech. At the end of the day, an agent is just a script with a loop and a brain. If you give it a clear goal and decent tools, it gets the job done. No need to over-engineer it! What are you building?`;
          } else {
            botContent = `That is a key question. Based on my research and core ideas from the episodes, I always assert that true technology leverage comes from building systems that adapt autonomously rather than follow rigid, pre-scripted configurations.`;
          }
        }
      }
    }

    const botMsg = {
      id: `ath-${Date.now() + 1}`,
      role: "assistant",
      content: botContent,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      sources: twinRetrievedSources
    };

    setAiHostTwinHistory((prev) => [...prev, botMsg]);

    // Speak aloud if voice mode is active
    if (twinVoiceMode) {
      speakHostTwinText(botContent, twinPersonality, () => setIsHostSpeaking(true), () => setIsHostSpeaking(false));
    }
  };

  return (
    <PodcastContext.Provider
      value={{
        // DB
        podcasts,
        episodes,
        viralClips,
        emotionTimelines,
        knowledgeData,
        setKnowledgeData,
        audienceInsights,
        perspectives,

        // Actives
        activePodcast,
        activeEpisode,
        activePage,
        setActivePage,
        selectPodcast,
        selectEpisode,

        // Audio state
        isPlaying,
        setIsPlaying,
        currentTime,
        setCurrentTime,
        playbackSpeed,
        setPlaybackSpeed,
        volume,
        setVolume,
        skipForward,
        skipBackward,
        formatTime,
        
        // Skip & Swap logs
        skipEvents,
        setSkipEvents,
        podcastSwaps,
        setPodcastSwaps,
        getInterpolatedEmotion,

        // Actions
        uploadPodcast,
        deletePodcast,
        searchQuery,
        setSearchQuery,

        // Chat
        chatHistory,
        sendChatMessage,
        aiHostTwinHistory,
        sendHostTwinMessage,
        compareModes,
        setCompareModes,
        getEpisodeTopics,
        getTimestampExplanation,

        // Host settings
        twinPersonality,
        setTwinPersonality,
        twinVoiceMode,
        setTwinVoiceMode,
        isHostSpeaking,
        setIsHostSpeaking,

        // Global UI / Modals / Toast / Role / Integrations
        isUpgradeModalOpen,
        setIsUpgradeModalOpen,
        isApiConfigModalOpen,
        setIsApiConfigModalOpen,
        toast,
        showToast,
        userRole,
        setUserRole,
        avatar,
        setAvatar,
        isSidebarOpen,
        setIsSidebarOpen,
        apiConfig,
        setApiConfig,
        updatePodcastDetails,

        // Vector DB exports
        vectorDbSettings,
        setVectorDbSettings,
        vectorDbStats,
        isVectorIndexing,
        rebuildVectorIndex,
        vectorStoreRef
      }}
    >
      {children}
    </PodcastContext.Provider>
  );
};

export const usePodcast = () => useContext(PodcastContext);
